### ISSUE TITLE
how to generate the .npy file from .world file?

### ISSUE THREAD

**Issue by gogov5** [cdthompson/deepracer-k1999-race-lines#1]
I find that the AWS provide .world file , but how to get the .npy file  for the new tracks? 

eg.  the track  Championship Cup Warm-up  2019

thanks

**Comment by cdthompson** [comment]
It's not trivial to generate the npy file from the world file.  If you have access to the world files, there should be an npy file also available in the robomaker simapp bundle.  I've also added it to the repo here with a good pass at the race line calculation.

**Comment by gogov5** [comment]
got it, thanks , this race-line tool is very useful
