### ISSUE TITLE
Error when running the /deepracer-k1999-race-lines/Race-Line-Calculation.ipynb

### ISSUE THREAD

**Issue by new4u** [cdthompson/deepracer-k1999-race-lines#2]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[8], line 14
     12 l_inner_border = LineString(inner_border)
     13 l_outer_border = LineString(outer_border)
---> 14 road_poly = Polygon(np.vstack((l_outer_border, np.flipud(l_inner_border))))
     15 print("Is loop[/ring](https://vscode-remote+codespaces-002bnew4u-002danimated-002dmeme-002dr4x97w7jgqp2xgvw.vscode-resource.vscode-cdn.net/ring)? ", l_center_line.is_ring)
     16 road_poly

File <__array_function__ internals>:200, in flipud(*args, **kwargs)

File [~/.local/lib/python3.10/site-packages/numpy/lib/twodim_base.py:154](https://vscode-remote+codespaces-002bnew4u-002danimated-002dmeme-002dr4x97w7jgqp2xgvw.vscode-resource.vscode-cdn.net/workspaces/aws_deepracer_worksheet/deepracer-k1999-race-lines/~/.local/lib/python3.10/site-packages/numpy/lib/twodim_base.py:154), in flipud(m)
    152 m = asanyarray(m)
    153 if m.ndim < 1:
--> 154     raise ValueError("Input must be >= 1-d.")
    155 return m[::-1, ...]

ValueError: Input must be >= 1-d.

**Comment by mburns7211** [comment]
I am also facing the same issue, has this been resolved?

**Comment by cdthompson** [comment]
Sorry, this code isn’t actively maintained.

**Comment by mburns7211** [comment]
The following resolved the issue

flipped = np.flipud(list(l_inner_border.coords))
line_tuple = (list(l_outer_border.coords), flipped)

**Comment by jagadeeshkmanne** [comment]
@mburns7211 Can you please provide the working code. I am also facing the same issue but i am new to python and unable to understand
